In [38]:
import pandas as pd
import numpy as np
import datetime
from synthdid.synthdid import Synthdid

In [44]:
data = pd.read_csv('../temporary/data_sdid.csv', parse_dates=['time'])
country_data = pd.read_csv('../temporary/country_data.csv')

In [31]:
data.head()

,user_cc,time,outflow,time_number,country_number,BJ,CA,CM,DE,GB,GH,IN,NG,NL,ZA
0,AD,2017-03-12,0.0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,AD,2017-03-19,0.0,2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,AD,2017-03-26,0.0,3,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,AD,2017-04-02,0.0,4,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,AD,2017-04-09,0.0,5,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [24]:
def initialize_sdid(data, window_start, window_end, treated_unit, treatment_start):
    df = data[(data['time'] >= window_start) & (data['time'] <= window_end)].copy()

    #create dummy for treatment
    df['treated'] = ((df['user_cc'] == treated_unit) & (df['time'] >= treatment_start)).astype(int)
    
    #intialize SDID object
    sdid = Synthdid(data = df, unit = "user_cc", time = "time", treatment="treated", outcome="outflow")
    return sdid

In [48]:
test = initialize_sdid(data=data, window_start = '2020-01-01', window_end='2020-06-07', treated_unit='US', treatment_start='2020-04-09')

TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)

In [28]:
from synthdid.get_data import california_prop99

cali_data = california_prop99()

In [29]:
cali_data

              State  Year  PacksPerCapita  treated
0           Alabama  1970       89.800003        0
1          Arkansas  1970      100.300003        0
2          Colorado  1970      124.800003        0
3       Connecticut  1970      120.000000        0
4          Delaware  1970      155.000000        0
...             ...   ...             ...      ...
1204       Virginia  2000       96.699997        0
1205  West Virginia  2000      107.900002        0
1206      Wisconsin  2000       80.099998        0
1207        Wyoming  2000       90.500000        0
1208     California  2000       41.599998        1

[1209 rows x 4 columns]